<!--
document.write("<form><div class='area'><div class='monitor'>")
document.write("<a href='JavaScript:clickImage(1)' onMouseOver='selectImage(1)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(2)' onMouseOver='selectImage(2)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(3)' onMouseOver='selectImage(3)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(4)' onMouseOver='selectImage(4)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(5)' onMouseOver='selectImage(5)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(6)' onMouseOver='selectImage(6)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(7)' onMouseOver='selectImage(7)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(8)' onMouseOver='selectImage(8)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(9)' onMouseOver='selectImage(9)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(10)' onMouseOver='selectImage(10)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(11)' onMouseOver='selectImage(11)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(12)' onMouseOver='selectImage(12)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(13)' onMouseOver='selectImage(13)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(14)' onMouseOver='selectImage(14)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(15)' onMouseOver='selectImage(15)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(16)' onMouseOver='selectImage(16)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(17)' onMouseOver='selectImage(17)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(18)' onMouseOver='selectImage(18)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(19)' onMouseOver='selectImage(19)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(20)' onMouseOver='selectImage(20)'><img src='0.png'></a>")
document.write("<br>")
document.write("<a href='JavaScript:clickImage(21)' onMouseOver='selectImage(21)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(22)' onMouseOver='selectImage(22)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(23)' onMouseOver='selectImage(23)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(24)' onMouseOver='selectImage(24)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(25)' onMouseOver='selectImage(25)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(26)' onMouseOver='selectImage(26)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(27)' onMouseOver='selectImage(27)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(28)' onMouseOver='selectImage(28)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(29)' onMouseOver='selectImage(29)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(30)' onMouseOver='selectImage(30)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(31)' onMouseOver='selectImage(31)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(32)' onMouseOver='selectImage(32)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(33)' onMouseOver='selectImage(33)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(34)' onMouseOver='selectImage(34)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(35)' onMouseOver='selectImage(35)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(36)' onMouseOver='selectImage(36)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(37)' onMouseOver='selectImage(37)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(38)' onMouseOver='selectImage(38)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(39)' onMouseOver='selectImage(39)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(40)' onMouseOver='selectImage(40)'><img src='0.png'></a>")
document.write("<br>")
document.write("<a href='JavaScript:clickImage(41)' onMouseOver='selectImage(41)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(42)' onMouseOver='selectImage(42)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(43)' onMouseOver='selectImage(43)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(44)' onMouseOver='selectImage(44)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(45)' onMouseOver='selectImage(45)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(46)' onMouseOver='selectImage(46)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(47)' onMouseOver='selectImage(47)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(48)' onMouseOver='selectImage(48)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(49)' onMouseOver='selectImage(49)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(50)' onMouseOver='selectImage(50)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(51)' onMouseOver='selectImage(51)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(52)' onMouseOver='selectImage(52)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(53)' onMouseOver='selectImage(53)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(54)' onMouseOver='selectImage(54)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(55)' onMouseOver='selectImage(55)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(56)' onMouseOver='selectImage(56)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(57)' onMouseOver='selectImage(57)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(58)' onMouseOver='selectImage(58)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(59)' onMouseOver='selectImage(59)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(60)' onMouseOver='selectImage(60)'><img src='0.png'></a>")
document.write("<br>")
document.write("<a href='JavaScript:clickImage(61)' onMouseOver='selectImage(61)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(62)' onMouseOver='selectImage(62)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(63)' onMouseOver='selectImage(63)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(64)' onMouseOver='selectImage(64)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(65)' onMouseOver='selectImage(65)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(66)' onMouseOver='selectImage(66)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(67)' onMouseOver='selectImage(67)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(68)' onMouseOver='selectImage(68)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(69)' onMouseOver='selectImage(69)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(70)' onMouseOver='selectImage(70)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(71)' onMouseOver='selectImage(71)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(72)' onMouseOver='selectImage(72)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(73)' onMouseOver='selectImage(73)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(74)' onMouseOver='selectImage(74)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(75)' onMouseOver='selectImage(75)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(76)' onMouseOver='selectImage(76)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(77)' onMouseOver='selectImage(77)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(78)' onMouseOver='selectImage(78)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(79)' onMouseOver='selectImage(79)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(80)' onMouseOver='selectImage(80)'><img src='0.png'></a>")
document.write("<br>")
document.write("<a href='JavaScript:clickImage(81)' onMouseOver='selectImage(81)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(82)' onMouseOver='selectImage(82)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(83)' onMouseOver='selectImage(83)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(84)' onMouseOver='selectImage(84)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(85)' onMouseOver='selectImage(85)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(86)' onMouseOver='selectImage(86)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(87)' onMouseOver='selectImage(87)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(88)' onMouseOver='selectImage(88)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(89)' onMouseOver='selectImage(89)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(90)' onMouseOver='selectImage(90)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(91)' onMouseOver='selectImage(91)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(92)' onMouseOver='selectImage(92)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(93)' onMouseOver='selectImage(93)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(94)' onMouseOver='selectImage(94)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(95)' onMouseOver='selectImage(95)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(96)' onMouseOver='selectImage(96)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(97)' onMouseOver='selectImage(97)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(98)' onMouseOver='selectImage(98)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(99)' onMouseOver='selectImage(99)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(100)' onMouseOver='selectImage(100)'><img src='0.png'></a>")
document.write("<br>")
document.write("<a href='JavaScript:clickImage(101)' onMouseOver='selectImage(101)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(102)' onMouseOver='selectImage(102)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(103)' onMouseOver='selectImage(103)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(104)' onMouseOver='selectImage(104)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(105)' onMouseOver='selectImage(105)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(106)' onMouseOver='selectImage(106)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(107)' onMouseOver='selectImage(107)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(108)' onMouseOver='selectImage(108)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(109)' onMouseOver='selectImage(109)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(110)' onMouseOver='selectImage(110)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(111)' onMouseOver='selectImage(111)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(112)' onMouseOver='selectImage(112)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(113)' onMouseOver='selectImage(113)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(114)' onMouseOver='selectImage(114)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(115)' onMouseOver='selectImage(115)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(116)' onMouseOver='selectImage(116)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(117)' onMouseOver='selectImage(117)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(118)' onMouseOver='selectImage(118)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(119)' onMouseOver='selectImage(119)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(120)' onMouseOver='selectImage(120)'><img src='0.png'></a>")
document.write("<br>")
document.write("<a href='JavaScript:clickImage(121)' onMouseOver='selectImage(121)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(122)' onMouseOver='selectImage(122)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(123)' onMouseOver='selectImage(123)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(124)' onMouseOver='selectImage(124)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(125)' onMouseOver='selectImage(125)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(126)' onMouseOver='selectImage(126)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(127)' onMouseOver='selectImage(127)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(128)' onMouseOver='selectImage(128)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(129)' onMouseOver='selectImage(129)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(130)' onMouseOver='selectImage(130)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(131)' onMouseOver='selectImage(131)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(132)' onMouseOver='selectImage(132)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(133)' onMouseOver='selectImage(133)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(134)' onMouseOver='selectImage(134)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(135)' onMouseOver='selectImage(135)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(136)' onMouseOver='selectImage(136)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(137)' onMouseOver='selectImage(137)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(138)' onMouseOver='selectImage(138)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(139)' onMouseOver='selectImage(139)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(140)' onMouseOver='selectImage(140)'><img src='0.png'></a>")
document.write("<br>")
document.write("<a href='JavaScript:clickImage(141)' onMouseOver='selectImage(141)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(142)' onMouseOver='selectImage(142)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(143)' onMouseOver='selectImage(143)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(144)' onMouseOver='selectImage(144)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(145)' onMouseOver='selectImage(145)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(146)' onMouseOver='selectImage(146)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(147)' onMouseOver='selectImage(147)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(148)' onMouseOver='selectImage(148)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(149)' onMouseOver='selectImage(149)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(150)' onMouseOver='selectImage(150)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(151)' onMouseOver='selectImage(151)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(152)' onMouseOver='selectImage(152)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(153)' onMouseOver='selectImage(153)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(154)' onMouseOver='selectImage(154)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(155)' onMouseOver='selectImage(155)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(156)' onMouseOver='selectImage(156)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(157)' onMouseOver='selectImage(157)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(158)' onMouseOver='selectImage(158)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(159)' onMouseOver='selectImage(159)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(160)' onMouseOver='selectImage(160)'><img src='0.png'></a>")
document.write("<br>")
document.write("<a href='JavaScript:clickImage(161)' onMouseOver='selectImage(161)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(162)' onMouseOver='selectImage(162)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(163)' onMouseOver='selectImage(163)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(164)' onMouseOver='selectImage(164)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(165)' onMouseOver='selectImage(165)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(166)' onMouseOver='selectImage(166)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(167)' onMouseOver='selectImage(167)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(168)' onMouseOver='selectImage(168)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(169)' onMouseOver='selectImage(169)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(170)' onMouseOver='selectImage(170)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(171)' onMouseOver='selectImage(171)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(172)' onMouseOver='selectImage(172)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(173)' onMouseOver='selectImage(173)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(174)' onMouseOver='selectImage(174)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(175)' onMouseOver='selectImage(175)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(176)' onMouseOver='selectImage(176)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(177)' onMouseOver='selectImage(177)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(178)' onMouseOver='selectImage(178)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(179)' onMouseOver='selectImage(179)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(180)' onMouseOver='selectImage(180)'><img src='0.png'></a>")
document.write("<br>")
document.write("<a href='JavaScript:clickImage(181)' onMouseOver='selectImage(181)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(182)' onMouseOver='selectImage(182)'><img src='0.png'></a>")
document.write("<a href='JavaScript:cli</amage(183)' onMouseOver='selectImage(183)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(184)' onMouseOver='selectImage(184)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(185)' onMouseOver='selectImage(185)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(186)' onMouseOver='selectImage(186)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(187)' onMouseOver='selectImage(187)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(188)' onMouseOver='selectImage(188)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(189)' onMouseOver='selectImage(189)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(190)' onMouseOver='selectImage(190)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(191)' onMouseOver='selectImage(191)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(192)' onMouseOver='selectImage(192)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(193)' onMouseOver='selectImage(193)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(194)' onMouseOver='selectImage(194)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(195)' onMouseOver='selectImage(195)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(196)' onMouseOver='selectImage(196)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(197)' onMouseOver='selectImage(197)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(198)' onMouseOver='selectImage(198)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(199)' onMouseOver='selectImage(199)'><img src='0.png'></a>")
document.write("<a href='JavaScript:clickImage(200)' onMouseOver='selectImage(200)'><img src='0.png'></a>")

document.write("</div><div class='result'><ul>")
document.write("<li><img src='1.png'><br><input type='text'></li>")
document.write("<li><img src='2.png'><br><input type='text'></li>")
document.write("<li><img src='3.png'><br><input type='text'></li>")
document.write("<li><img src='4.png'><br><input type='text'></li>")
document.write("<li><img src='5.png'><br><input type='text'></li>")
document.write("<li><span>残り</span>  <input type='text'></li>")
document.write("<li><span>スコア</span><input type='text'></li>")
document.write("</ul><ul class='btm'>")
document.write("<li class='select'>選択コマ数：<input type='text'>")
document.write("<li><input type='button' value='一手戻す' onClick='backGame()'>")
document.write("<li><input type='button' value='最初から' onClick='resetGame()'>")
document.write("</ul></div></div>")

resetGame();
//-->